from time import sleep

print("Hello, this is TerraBot, the launcher for all T.A.R.D.I.S appliances. Q.U.A.S.A.R is a new app that can activate any TARDIS device within 120000 Billion miles from your location. In later versions this distance will be expanded. There are 4 main TARDIS appliances. To activate one within your area, please sign in to QUASAR.")
print("Please enter your username by typing it and hitting enter.")
username = input()
print("PROCESSING...")
sleep(3)
print("Username accepted! Welcome to the TARDIS database," + username + " where the system will launch QUASAR.")
print("Please wait so QUASAR can launch.")
sleep(3)
print("LAUNCHING:")
print("10%")
sleep(0.99)
print("21%")
sleep(4)
print("35%")
sleep(2)
print("42%")
sleep(0.20)
print("56%")
sleep(6)
print("87%")
sleep(1)
print("99%")
sleep(0.99)
print("100%")
sleep(3)
print("LOADING COMPLETE! GREAT TO SEE YOU," + username + " !")
print(
