from time import sleep

print("Hello, this is TerraBot, the launcher for all T.A.R.D.I.S appliances. Q.U.A.S.A.R is a new app that can activate any TARDIS device within 120000 Billion miles from your location. In later versions this distance will be expanded. There are 4 main TARDIS appliances. To activate one within your area, please sign in to QUASAR.")
print("Please enter your username by typing it and hitting enter.")
username = input()
print("PROCESSING...")
sleep(3)
print("Username accepted! Welcome to the TARDIS database," + username + " where the system will launch QUASAR.")
print("Please wait so QUASAR can launch.")
sleep(3)
print("LAUNCHING:")
print("10%")
sleep(0.99)
print("21%")
sleep(4)
print("35%")
sleep(2)
print("42%")
sleep(0.20)
print("56%")
sleep(6)
print("87%")
sleep(1)
print("99%")
sleep(0.99)
print("100%")
sleep(3)
print("LOADING COMPLETE! GREAT TO SEE YOU," + username + " !")
print("YOU HAVE NOW ACCESSED QUASAR. WHAT DEVICE WOULD YOU LIKE TO ACCESS? PLEASE ENTER THE DEVICE NAME BELOW AND AFTER HITTING ENTER, THE OWNER. YOU WILL THEN HAVE TO ENTER A PASSWORD.")
print("PLEASE ENTER NOW:")
devicename = input()
print("PROCESSING...")
sleep(1)
print("...")
sleep(1)
print("...")
sleep(1)
print("...")
sleep(1)
print("...")
sleep(5)
print("RUNNING DATABASE SCAN:")
sleep(3)
print("56%")
sleep(3)
print("87%")
sleep(2)
print("99%")
sleep(0.99)
print("PLEASE ENTER OWNER USERNAME:")
owneruser = input()
sleep(3)
print("OWNER USERNAME ACCEPTED. PLEASE ENTER DEVICE PASSWORD.")
password = input()
print("CHECKING...")
sleep(4)
print("PASSWORD ACCEPTED. LOCATING APPLIANCE...")
sleep(5)
print("" + devicename + " LOCATED! SENDING NOW.")
print("THANK YOU FOR USING QUASAR! HAVE A NICE INTERGALACTIC YEAR!")
print("IF YOU WISH TO ACCESS ANOTHER DEVICE, PLEASE TYPE 'adnfh_accesskeyxxdc12' ON YOUR KEYBOARD AND THE WHOLE PROCESS WILL START ALL OVER AGAIN.")
accessotherdevice = input()
if accessotherdevice == "adnfh_accesskeyxxdc12":
    print("RESTARTING SYSTEMS...")
    sleep(5)
    print("LOADED.")
    print("YOU HAVE NOW ACCESSED QUASAR. WHAT DEVICE WOULD YOU LIKE TO ACCESS? PLEASE ENTER THE DEVICE NAME BELOW AND AFTER HITTING ENTER, THE OWNER. YOU WILL THEN HAVE TO ENTER A PASSWORD.")
print("PLEASE ENTER NOW:")
devicename = input()
print("PROCESSING...")
sleep(1)
print("...")
sleep(1)
print("...")
sleep(1)
print("...")
sleep(1)
print("...")
sleep(5)
print("RUNNING DATABASE SCAN:")
sleep(3)
print("56%")
sleep(3)
print("87%")
sleep(2)
print("99%")
sleep(0.99)
print("PLEASE ENTER OWNER USERNAME:")
owneruser = input()
sleep(3)
print("OWNER USERNAME ACCEPTED. PLEASE ENTER DEVICE PASSWORD.")
password = input()
print("CHECKING...")
sleep(4)
print("PASSWORD ACCEPTED. LOCATING APPLIANCE...")
sleep(5)
print("" + devicename + " LOCATED! SENDING NOW.")
print("THANK YOU FOR USING QUASAR! HAVE A NICE INTERGALACTIC YEAR!")
print("IF YOU WISH TO ACCESS ANOTHER DEVICE, PLEASE TYPE 'adnfh_accesskeyxxdc12' ON YOUR KEYBOARD AND THE WHOLE PROCESS WILL START ALL OVER AGAIN.")
accessotherdevice = input()
if accessotherdevice == "adnfh_accesskeyxxdc12":
    print("RESTARTING SYSTEMS...")
    sleep(5)
    print("LOADED.")
    print("YOU HAVE NOW ACCESSED QUASAR. WHAT DEVICE WOULD YOU LIKE TO ACCESS? PLEASE ENTER THE DEVICE NAME BELOW AND AFTER HITTING ENTER, THE OWNER. YOU WILL THEN HAVE TO ENTER A PASSWORD.")
print("PLEASE ENTER NOW:")
devicename = input()
print("PROCESSING...")
sleep(1)
print("...")
sleep(1)
print("...")
sleep(1)
print("...")
sleep(1)
print("...")
sleep(5)
print("RUNNING DATABASE SCAN:")
sleep(3)
print("56%")
sleep(3)
print("87%")
sleep(2)
print("99%")
sleep(0.99)
print("PLEASE ENTER OWNER USERNAME:")
owneruser = input()
sleep(3)
print("OWNER USERNAME ACCEPTED. PLEASE ENTER DEVICE PASSWORD.")
password = input()
print("CHECKING...")
sleep(4)
print("PASSWORD ACCEPTED. LOCATING APPLIANCE...")
sleep(5)
print("" + devicename + " LOCATED! SENDING NOW.")
print("THANK YOU FOR USING QUASAR! HAVE A NICE INTERGALACTIC YEAR!")
print("IF YOU WISH TO ACCESS ANOTHER DEVICE, PLEASE TYPE 'adnfh_accesskeyxxdc12' ON YOUR KEYBOARD AND THE WHOLE PROCESS WILL START ALL OVER AGAIN.")
accessotherdevice = input()
if accessotherdevice == "adnfh_accesskeyxxdc12":
    print("RESTARTING SYSTEMS...")
    sleep(5)
    print("LOADED.")
    print("YOU HAVE NOW ACCESSED QUASAR. WHAT DEVICE WOULD YOU LIKE TO ACCESS? PLEASE ENTER THE DEVICE NAME BELOW AND AFTER HITTING ENTER, THE OWNER. YOU WILL THEN HAVE TO ENTER A PASSWORD.")
print("PLEASE ENTER NOW:")
devicename = input()
print("PROCESSING...")
sleep(1)
print("...")
sleep(1)
print("...")
sleep(1)
print("...")
sleep(1)
print("...")
sleep(5)
print("RUNNING DATABASE SCAN:")
sleep(3)
print("56%")
sleep(3)
print("87%")
sleep(2)
print("99%")
sleep(0.99)
print("PLEASE ENTER OWNER USERNAME:")
owneruser = input()
sleep(3)
print("OWNER USERNAME ACCEPTED. PLEASE ENTER DEVICE PASSWORD.")
password = input()
print("CHECKING...")
sleep(4)
print("PASSWORD ACCEPTED. LOCATING APPLIANCE...")
sleep(5)
print("" + devicename + " LOCATED! SENDING NOW.")
print("THANK YOU FOR USING QUASAR! HAVE A NICE INTERGALACTIC YEAR!")
print("IF YOU WISH TO ACCESS ANOTHER DEVICE, PLEASE TYPE 'adnfh_accesskeyxxdc12' ON YOUR KEYBOARD AND THE WHOLE PROCESS WILL START ALL OVER AGAIN.")
accessotherdevice = input()
if accessotherdevice == "adnfh_accesskeyxxdc12":
    print("RESTARTING SYSTEMS...")
    sleep(5)
    print("LOADED.")
    print("YOU HAVE NOW ACCESSED QUASAR. WHAT DEVICE WOULD YOU LIKE TO ACCESS? PLEASE ENTER THE DEVICE NAME BELOW AND AFTER HITTING ENTER, THE OWNER. YOU WILL THEN HAVE TO ENTER A PASSWORD.")
print("PLEASE ENTER NOW:")
devicename = input()
print("PROCESSING...")
sleep(1)
print("...")
sleep(1)
print("...")
sleep(1)
print("...")
sleep(1)
print("...")
sleep(5)
print("RUNNING DATABASE SCAN:")
sleep(3)
print("56%")
sleep(3)
print("87%")
sleep(2)
print("99%")
sleep(0.99)
print("PLEASE ENTER OWNER USERNAME:")
owneruser = input()
sleep(3)
print("OWNER USERNAME ACCEPTED. PLEASE ENTER DEVICE PASSWORD.")
password = input()
print("CHECKING...")
sleep(4)
print("PASSWORD ACCEPTED. LOCATING APPLIANCE...")
sleep(5)
print("" + devicename + " LOCATED! SENDING NOW.")
print("THANK YOU FOR USING QUASAR! HAVE A NICE INTERGALACTIC YEAR!")
print("IF YOU WISH TO ACCESS ANOTHER DEVICE, PLEASE TYPE 'adnfh_accesskeyxxdc12' ON YOUR KEYBOARD AND THE WHOLE PROCESS WILL START ALL OVER AGAIN.")
accessotherdevice = input()
if accessotherdevice == "adnfh_accesskeyxxdc12":
    print("RESTART FAILED. MAXIMUM NUMBER OF APPLIANCES SENT OVER AT ONE TIME LIMIT REACHED. SHUTTING OFF...")
